In [108]:
import pandas as pd
df = pd.read_csv('merged_cleaned.csv')
df.head()

,Id,date,platform,title,News content,Label
0,1,2023-01-11,Aljazeera,شهداء في جنين وطولكرم وإضراب عام بالضفة الغربي...,استشهد 4 فلسطينيين واعتقل عشرات آخرون -اليوم ا...,real
1,2,2023-01-11,Aljazeera,الضفة الغربية.. الاحتلال يهدم 17 منزلا تاريخيا...,هدمت قوات الاحتلال الإسرائيلي -اليوم الأربعاء-...,real
2,3,2023-01-11,Aljazeera,مظاهرات بمدن أوروبية تضامنا مع غزة وحشود أمام ...,خرجت مظاهرات في عدد من المدن الأوروبية مساء ال...,real
3,4,2023-02-11,Aljazeera,أبو عبيدة: خسائر العدو أكبر بكثير مما يعلن وسن...,أكد الناطق باسمكتائب الشهيد عز الدين القسام-ال...,real
4,5,2023-03-11,Aljazeera,9 شهداء بالضفة والاحتلال يشن حملة اعتقالات,استشهد 9 فلسطينيين في مواجهات اندلعت مع قوات ا...,real

In [109]:
df.shape

(5352, 6)

In [103]:
df.count()

Id              5352
date            5352
platform        5352
title           5352
News content    5352
Label           5352
dtype: int64

In [104]:
# # حساب عدد كل combination من platform و label
platform_label_counts = df.groupby(['platform', 'Label']).size().reset_index(name='count')

platform_label_counts

                         platform Label  count
0                               1  real      1
1                             AFP  fake     15
2                  AFP Fact Check  fake      2
3                       Aljazeera  real   3422
4                        Facebook  fake     16
5                        Facebook  real      1
6                       Instagram  fake      5
7                          Misbar  fake   1061
8                          Misbar  real    365
9                         Reuters  fake     15
10             Reuters Fact Check  fake      2
11                         Tibyan  fake    174
12                         Tibyan  real     73
13                         TikTok  fake      2
14                        Twitter  fake      1
15                              X  fake     63
16                              X  real      1
17                        YouTube  fake      6
18                        chayyek  fake      1
19                         tayqan  fake      1
20   الاتحاد الفلسطيني لكرة القدم  real     15
21             الناشط حمزة المصري  fake     37
22               سلطة جودة البيئة  real      9
23        قناة النصيرات الإخبارية  fake     37
24  معبر كيسوفيم يستقبل 300 شاحنة  fake      1
25  وزارة التربية والتعليم العالي  real     10
26       وزارة التنمية الاجتماعية  real      9
27                  وزارة الثقافة  real      1
28      وزارة الخارجية والمغتربين  real      5
29         وزارة الصحة الفلسطينية  real      1

In [105]:
print(df.isna().sum())

Id              0
date            0
platform        0
title           0
News content    0
Label           0
dtype: int64

In [106]:
df['platform'].value_counts()

platform
Aljazeera                        3422
Misbar                           1426
Tibyan                            247
X                                  64
الناشط حمزة المصري                 37
قناة النصيرات الإخبارية            37
Facebook                           17
AFP                                15
الاتحاد الفلسطيني لكرة القدم       15
Reuters                            15
وزارة التربية والتعليم العالي      10
سلطة جودة البيئة                    9
وزارة التنمية الاجتماعية            9
YouTube                             6
وزارة الخارجية والمغتربين           5
Instagram                           5
TikTok                              2
Reuters Fact Check                  2
AFP Fact Check                      2
tayqan                              1
chayyek                             1
Twitter                             1
وزارة الصحة الفلسطينية              1
وزارة الثقافة                       1
1                                   1
معبر كيسوفيم يستقبل 300 شاحنة       1
Name: count, dtype: int64

In [107]:
print(df.isnull().sum())

Id              0
date            0
platform        0
title           0
News content    0
Label           0
dtype: int64